name: Auto approve
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for build to succeed
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-build
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build
    - uses: hmarr/auto-approve-action@v2
      if: steps.wait-for-build.outputs.conclusion == 'success'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
