name: my test
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo "::set-output name=mytest1::123"
  job2:
     needs: job1
     runs-on: ubuntu-latest
     env:
       DATA: ${{needs.job1.outputs.mytest}}
     steps:
     - name: test2
       run: echo "$(DATA)";echo "$(date)"
