name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: public/
      - name: next_tag
        run: |
          echo "::set-output name=next_tag::$( git tag --sort=creatordate | tail -1 | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')"
        id: next_tag_info
      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.next_tag_info.outputs.next_tag }}
