# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check-out
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: test-script
      id: test-script
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: return "Hello!"
        result-encoding: string
    - name: Get Result
      run: "${{steps.test-script.outputs.result}}"
        