name: Auto Check Approver Merger
on: pull_request_target

jobs:

  check_condition:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for build to succeed
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-build
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build123
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - uses: hmarr/auto-approve-action@v2
      if: steps.wait-for-build.outputs.conclusion == 'success'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
  automerge:
    needs: check_condition
    runs-on: ubuntu-latest
    steps:
    - name: Merge pull requests (automerge-action)
      uses: pascalgn/automerge-action@v0.14.3
      env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          #LOG: "TRACE"  # or "DEBUG"
          
  createTag:
    needs: automerge
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: next_tag
      if: github.repository == 'cedricwong1/github-actions-for-ci'
      run: |
          echo "::set-output name=next_tag::$( git tag --sort=creatordate | tail -1 | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')"
      id: next_tag_info   
    - name: check_merge_status
      if: github.repository == 'cedricwong1/github-actions-for-ci'
      run: |
          echo "::set-output name=merge_status::$([[ $(git rev-parse HEAD) == $(git rev-list -n 1 $(git tag --sort=creatordate | tail -1)) ]] && echo "false" || echo "true")"
          echo $(git rev-parse HEAD)
          echo $(git rev-list -n 1 $(git tag --sort=creatordate | tail -1))
      id: check_merge_status
    - name: push_new_tag
      if: (github.repository == 'cedricwong1/github-actions-for-ci' && steps.check_merge_status.outputs.merge_status=='true' )
      uses: actions-ecosystem/action-push-tag@v1
      with:
          tag: ${{ steps.next_tag_info.outputs.next_tag }}
