name: Auto Check Approver Merger
on: pull_request_target

jobs:

  check_condition:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for build to succeed
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-build
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build123
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - uses: hmarr/auto-approve-action@v2
      if: steps.wait-for-build.outputs.conclusion == 'success'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
  automerge:
    needs: check_condition
    runs-on: ubuntu-latest
    steps:
    - name: Merge pull requests (automerge-action)
      uses: pascalgn/automerge-action@v0.14.3
      env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          #LOG: "TRACE"  # or "DEBUG"
  dispatch:
    needs: automerge
    runs-on: ubuntu-latest
    steps:
    - name: Wait for merge to succeed
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-merge
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: automerge
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - name: Invoke workflow without inputs
      uses: benc-uk/workflow-dispatch@v1
      with:
          workflow: Node CI
          token: ${{ secrets.DEVOPS_TOKEN }}

